version: '3.7'
services:
  gitea:
    image: gitea/gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    volumes:
      - gitea-data:/data
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
    restart: always

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
     - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea

  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
     - jenkins-data:/var/jenkins_home

  terraform:
    image: hashicorp/terraform

  registy:
    image: registry
    ports:
      - 5000:5000
    volumes:
     - registry-data:/var/lib/registry

volumes:
    gitea-data:
    db-data:
    jenkins-data:
    registry-data: