version: '3.7'

services:
  jenkins-master:
    image: haven/jenkins
    ports:
      - '7070:8080'
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins-home:
